[toolchain]
channel = "nightly-2025-08-02" 
# Latest nightly not working at the moment
# https://github.com/rust-lang/rust/issues/145151
components = [
  "rust-src",
  "rust-analyzer",
  "rustfmt",
  "llvm-tools-preview",
  "rustc-codegen-cranelift-preview",
]
