[toolchain]
channel = "nightly"
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
components = [
  "rust-src",
  "rust-analyzer",
  "rustfmt",
  "llvm-tools-preview",
  "rustc-codegen-cranelift-preview",
]
